/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { CognitionContract } from "./Cognition";
import { ERC165Contract } from "./ERC165";
import { ERC721Contract } from "./ERC721";
import { ERC721EnumerableContract } from "./ERC721Enumerable";
import { ERC721FullContract } from "./ERC721Full";
import { ERC721URIStorageContract } from "./ERC721URIStorage";
import { IERC165Contract } from "./IERC165";
import { IERC721Contract } from "./IERC721";
import { IERC721EnumerableContract } from "./IERC721Enumerable";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { MigrationsContract } from "./Migrations";
import { StroopRewardContract } from "./StroopReward";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Cognition"): CognitionContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "ERC721Enumerable"): ERC721EnumerableContract;
      require(name: "ERC721Full"): ERC721FullContract;
      require(name: "ERC721URIStorage"): ERC721URIStorageContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Enumerable"): IERC721EnumerableContract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "StroopReward"): StroopRewardContract;
    }
  }
}

export { CognitionContract, CognitionInstance } from "./Cognition";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export {
  ERC721EnumerableContract,
  ERC721EnumerableInstance,
} from "./ERC721Enumerable";
export { ERC721FullContract, ERC721FullInstance } from "./ERC721Full";
export {
  ERC721URIStorageContract,
  ERC721URIStorageInstance,
} from "./ERC721URIStorage";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721EnumerableContract,
  IERC721EnumerableInstance,
} from "./IERC721Enumerable";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { StroopRewardContract, StroopRewardInstance } from "./StroopReward";
