import { ULHorizontalLinkType } from "../components/navigation/ULlinks"

// Crypto
export const ADD_WALLET_ADDRESS = 'ADD_WALLET_ADDRESS'
export const REMOVE_WALLET_ADDRESS = 'REMOVE_WALLET_ADDRESS'
export const SET_WALLET_BALANCE = 'SET_WALLET_BALANCE'
export const SET_WALLET_FIAT_BALANCE = 'SET_WALLET_FIAT_BALANCE'
export const SET_CURRENCY = 'SET_CURRENCY'
export const ADD_TOKEN_CONVERSION = 'ADD_TOKEN_CONVERSION'
export const ADD_REWARD_HISTORY = 'ADD_REWARD_HISTORY'
export const ADD_HISTORIC_PRICES = 'ADD_HISTORIC_PRICES'
export const ADD_CURRENT_PRICE = 'ADD_CURRENT_PRICE'

//Equities
export const SUBTRACT_FROM_REMAINING_PORTFOLIO_WEIGHT = 'SUBTRACT_FROM_REMAINING_PORTFOLIO_WEIGHT'
export const ADD_TO_REMAINING_PORTFOLIO_WEIGHT = "ADD_TO_REMAINING_PORTFOLIO_WEIGHT"
export const ADD_ETF_TO_PORTFOLIO = "ADD_ETF_TO_PORTFOLIO";
export const REMOVE_ETF_FROM_PORTFOLIO = 'REMOVE_ETF_FROM_PORTFOLIO'
export const ADD_ETF_HOLDINGS = "ADD_ETF_HOLDINGS";
export const SET_STOCK_OVERLAP = "SET_STOCK_OVERLAP"

export const demoAddresses = {
    'Polkadot': [
        '13Lzu5zu91j3mqiGp1MnqzdP3wXQpiwxgJAvvvjQ5shkDLFq',
        '15LHo8VrWYqT7PU6icmMjNbqGykZsLV9ZaBM4ywf75E9D9r9',
        '15r5PsVRr9rPv2F7GmHtH8a8mGZQ9MLFV6eYuW7FtRQDrnew',
        '12jMGHqnpEcvMbmiXav41dgDp64LMzrqhiYryAryXuCdAaoQ',
        '15Y9ugJMFKr5aichY8QHfAkemn4PpRe848rZtG2khUXW2M7y'
    ],
    'Tezos': [
        'tz1VJWdUyUohNARTw13TPWYvnC3qSTgUSNdV',
        'tz1WMnVGR45iCYTdVJhZcqJNSABYsiuyMFQZ',
        'tz1bi7iZyxPCGjMUQMiouiHRxQwveQjuTu8b',
        'tz1ZeRsv3qTfoKAzfaJLSGtqXpnJeUTM8BHg',
        'tz1SB4Pkpf43vaz9yQ5KYE3vQCg4gFC8BniQ'
    ],
    // 'Stellar': [
    //     'GB5KBM2OYTONCXYBLUZNX2S5ATI4CMQWVPD6MBWTSSHJ5FEENOHE4VL7',
    //     'GCXY377Y3FZ246OMLG6YMLJABCM4SWZ4FSOCOL3D6JYTLHRQIOT6AM7C',
    //     'GD7EEGIDKNVQ652KSOYJMHNIY2X6KSRHCTSUFDJHWBZ67ZPPFBU6FPQA',
    //     'GBXXMYQVDOZNVHLJ6JFRYLJVYXUT4DIMPBNJSYDOE5DLWRBW6P35FPZ2',
    //     'GDZTVC3WGBXM4CGZUL3DLXW6THREC5AIMBYPBHK7BV2YVO3QGKLUB5LU'
    // ],
    'Algorand': [
        'AHTWZF5QB52VMRK6VDJFYA6BDJF6X46VVZGPSCZRU6XWJZHPVZSPUS4M6I',
        'CYQRLBMQN5LCV75ICCKSZWRFCJ3CJVFXGOLSUNJ3IZKWS6SZGAZENKNKZY',
        'LCXEXPU2VM7AX7MGOR3UXL2PVDNB35CJ64ZQYKAMKJ7WMIEIS6ORL6ULZM',
        '5HPTEFTYANGI3HFY7GNOQL3SY4VY76ZY7E5TNZVEGFQ2UQLJE4HGP4SE6I',
        'LCXJNFMEU4ZD56KQD2COKQZVZRUWZDT2UWCRXAWZVLEMFMIXRQXFR5NOOE',
    ]
}

export const gamesLinkMap: ULHorizontalLinkType[] = [
    { url: '/memory', name: 'Memory' },
    { url: '/stroop', name: 'Stroop Effect' }
]

